import type { NextPage } from 'next';
import Head from 'next/head';
import { Order, useGetOrderQuery } from '../src/graphql/generated';
import styles from '../styles/Home.module.css';

const Info = ({ order }: { order: Order | null | undefined }) => {
  if (order == null) {
    return <div>No order found</div>;
  }

  return (
    <table className={styles.table}>
      <tbody>
        <tr>
          <td>Created: </td>
          <td>b</td>
        </tr>
        <tr>
          <td>id: </td>
          <td>{order.orderId}</td>
        </tr>
        <tr>
          <td>Status:</td>
          <td>
            <ul>
              <li>{order.orderValid ? '✅' : '❌'} - Order validation</li>
              <li>{order.paymentValid ? '✅' : '❌'} - Your payment</li>
              <li>
                {order.restaurantApproved ? '✅' : '❌'} - Restaurant approval
              </li>
              <li>{order.driverAssigned ? '✅' : '❌'} - Driver assignment</li>
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
  );

  // return (
  //   <ul>
  //     {Object.entries(order).map(([key, value]) => {
  //       if (key === '__typename') {
  //         return null;
  //       }

  //       return (
  //         <li key={`${key}-${value}`}>
  //           {key}: {value}
  //         </li>
  //       );
  //     })}
  //   </ul>
  // );
};

const Home: NextPage = () => {
  const [{ data }] = useGetOrderQuery({
    variables: {
      orderId: '16b33401-0e98-490a-836f-d8a2f49ff69c',
    },
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Info order={data?.getOrder} />

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
